# Generated by Django 4.0.3 on 2023-03-08 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_sale_automobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='automobile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='sales_rest.automobilevo'),
        ),
    ]
